### ISSUE TITLE
Editing Local Files - Trouble Switching Branches

### ISSUE THREAD

**Issue by loranallensmith** [certify/curriculum-github#86] opened 2015-07-08 03:09 UTC
I'm not sure if this is the right place to open this particular Issue, so definitely let me know if this thread should live somewhere else. :smiley:

In the module [`CONT-CLI-03_Editing-local-files.yml`](https://github.com/certify/curriculum-github/blob/master/modules/CONT-CLI-03_Editing-local-files.yml), the demonstration instructions say that you should check out the `master` branch after making changes on your `bio` branch.  I noticed that you can't easily switch back to master without first stashing your changes.  When I try to checkout `master` Git won't let me. :frowning: 

@crichID does this work for you?  I may be missing a step.

**Comment by crichID** [comment] 2015-07-08 03:46
@loranallensmith so, the problem is that we are trying to compare the branches before we have committed our changes to the branch. I can switch branches without stashing, but the modified file comes with me to the new branch so it still messes up the learning point. Really, this whole bit about switching branches to see the changes needs to be moved to the end of the video for CONT-CLI-04. I will PR the changes in the curriculum files - do you think you will be able to slice and dice the audio and make it work? Or do I need to re-record those two sections?

**Comment by loranallensmith** [comment] 2015-07-08 04:28
@crichID I think you read my mind on this one. :smiley_cat:   I nearly PRed that exact change to the curriculum tonight, but I didn't want to do anything too drastic on my own. :see_no_evil:   

I think I can make everything work with the videos. :+1:

**Closed as completed** 2015-07-08 20:29 UTC
